# write_cases_py.py
import duckdb
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
DUCKDB_PATH = PROJECT_DIR / "generated" / "vtnet.duckdb"
CASES_FILE = PROJECT_DIR / "benchmark" / "cases.py"

EASY_CASES = [
    ("E001", "Đếm tổng số tỉnh duy nhất trong danh mục địa bàn f_location_new.", "common_location",
     "SELECT COUNT(DISTINCT province_code) AS total_provinces FROM hive__netbi__f_location_new;",
     "SELECT COUNT(DISTINCT province_code) AS total_provinces FROM hive.netbi.f_location_new;",
     ["hive.netbi.f_location_new"], ["count_distinct", "simple_lookup"]),
    ("E002", "Liệt kê danh sách mã tỉnh và tên tỉnh thuộc Khu vực 1 (AREA_1) từ bảng địa bàn f_location_new.", "common_location",
     "SELECT DISTINCT province_code, province_name FROM hive__netbi__f_location_new WHERE area_code = 'AREA_1' ORDER BY province_code;",
     "SELECT DISTINCT province_code, province_name FROM hive.netbi.f_location_new WHERE area_code = 'AREA_1' ORDER BY province_code;",
     ["hive.netbi.f_location_new"], ["filtering", "simple_lookup"]),
    ("E003", "Đếm số lượng cell 5G có trong danh sách loại trừ occean_cell.", "network_kpi_5g",
     "SELECT COUNT(*) AS total_ocean_cells FROM hive__npms__occean_cell WHERE cell_type = '5G_NR';",
     "SELECT COUNT(*) AS total_ocean_cells FROM hive.npms.occean_cell WHERE cell_type = '5G_NR';",
     ["hive.npms.occean_cell"], ["filtering", "aggregation"]),
    ("E004", "Đếm số lượng tài khoản FTTH PPPoE thuộc nhóm khách hàng VIP (groupname = 'FTTH_VIP').", "fbb",
     "SELECT COUNT(*) AS total_vip_users FROM hive__aaa__ftth_account_pppoe WHERE groupname = 'FTTH_VIP';",
     "SELECT COUNT(*) AS total_vip_users FROM hive.aaa.ftth_account_pppoe WHERE groupname = 'FTTH_VIP';",
     ["hive.aaa.ftth_account_pppoe"], ["filtering", "aggregation"]),
    ("E005", "Liệt kê mã phòng ban và tên phòng ban thuộc khối NOC trong danh mục GNOC.", "alarm",
     "SELECT dept_code, dept_name FROM hive__gnoc__cat_department WHERE dept_code LIKE 'NOC_%' ORDER BY dept_code;",
     "SELECT dept_code, dept_name FROM hive.gnoc.cat_department WHERE dept_code LIKE 'NOC_%' ORDER BY dept_code;",
     ["hive.gnoc.cat_department"], ["pattern_matching", "simple_lookup"]),
    ("E006", "Lấy danh sách các nhóm giám sát dữ liệu có mã id nhỏ hơn hoặc bằng 2 trong bảng groups.", "data_monitoring",
     "SELECT id, name FROM mysql_datamon__data_monitoring__groups WHERE id <= 2 ORDER BY id;",
     "SELECT id, name FROM mysql_datamon.data_monitoring.groups WHERE id <= 2 ORDER BY id;",
     ["mysql_datamon.data_monitoring.groups"], ["filtering", "simple_lookup"]),
    ("E007", "Đếm tổng số bản ghi trong danh sách đen người dùng theo khu vực có id <= 15.", "data_monitoring",
     "SELECT COUNT(*) AS total_blacklist FROM mysql_datamon__data_monitoring__usersinarea_blacklist WHERE id <= 15;",
     "SELECT COUNT(*) AS total_blacklist FROM mysql_datamon.data_monitoring.usersinarea_blacklist WHERE id <= 15;",
     ["mysql_datamon.data_monitoring.usersinarea_blacklist"], ["filtering", "aggregation"]),
    ("E008", "Đếm số lượng bản ghi KPI 5G tại tỉnh Hà Nội (HNI) trong ngày 2026-08-20.", "network_kpi_5g",
     "SELECT COUNT(*) AS total_records FROM hive__npms__kpi_access5g_5g_cell_peak_view WHERE province_code = 'HNI' AND date_hour = '2026-08-20-00';",
     "SELECT COUNT(*) AS total_records FROM hive.npms.kpi_access5g_5g_cell_peak_view WHERE province_code = 'HNI' AND date_hour = '2026-08-20-00';",
     ["hive.npms.kpi_access5g_5g_cell_peak_view"], ["filtering", "aggregation"]),
    ("E009", "Lấy 5 cell 5G có thông lượng người dùng tải xuống cao nhất trong ngày 2026-08-20.", "network_kpi_5g",
     "SELECT object_id, CAST(dl_user_throughput_mbps AS DOUBLE) AS throughput FROM hive__npms__kpi_access5g_5g_cell_peak_view WHERE date_hour = '2026-08-20-00' ORDER BY throughput DESC, object_id ASC LIMIT 5;",
     "SELECT object_id, CAST(dl_user_throughput_mbps AS DOUBLE) AS throughput FROM hive.npms.kpi_access5g_5g_cell_peak_view WHERE date_hour = '2026-08-20-00' ORDER BY throughput DESC, object_id ASC LIMIT 5;",
     ["hive.npms.kpi_access5g_5g_cell_peak_view"], ["sorting", "limit"]),
    ("E010", "Đếm tổng số sự kiện cảnh báo sự cố nghiêm trọng (CRITICAL) được ghi nhận trong bảng gnoc.", "alarm",
     "SELECT COUNT(*) AS total_alarms FROM hive__gnoc__gnoc WHERE level_important = 'CRITICAL';",
     "SELECT COUNT(*) AS total_alarms FROM hive.gnoc.gnoc WHERE level_important = 'CRITICAL';",
     ["hive.gnoc.gnoc"], ["filtering", "aggregation"]),
    ("E011", "Lấy danh sách các máy chủ xác thực sbr_server duy nhất trong bảng authentication.", "fbb",
     "SELECT DISTINCT sbr_server FROM hive__aaa__authentication ORDER BY sbr_server;",
     "SELECT DISTINCT sbr_server FROM hive.aaa.authentication ORDER BY sbr_server;",
     ["hive.aaa.authentication"], ["distinct", "simple_lookup"]),
    ("E012", "Đếm số lượng sự kiện xác thực có số lượt chấp thuận (accept) lớn hơn 150.", "fbb",
     "SELECT COUNT(*) AS total_events FROM hive__aaa__authentication WHERE CAST(accept AS INT) > 150;",
     "SELECT COUNT(*) AS total_events FROM hive.aaa.authentication WHERE CAST(accept AS INT) > 150;",
     ["hive.aaa.authentication"], ["filtering", "type_cast"]),
    ("E013", "Liệt kê các nhà cung cấp thiết bị (vendor) khác nhau trong bảng sự kiện gnoc.", "alarm",
     "SELECT DISTINCT vendor FROM hive__gnoc__gnoc WHERE vendor != '' ORDER BY vendor;",
     "SELECT DISTINCT vendor FROM hive.gnoc.gnoc WHERE vendor != '' ORDER BY vendor;",
     ["hive.gnoc.gnoc"], ["distinct", "simple_lookup"]),
    ("E014", "Tính thông lượng tải xuống trung bình của mạng 4G trong ngày 2026-08-20.", "network_kpi_4g",
     "SELECT ROUND(AVG(CAST(dl_cell_throughput_mbps AS DOUBLE)), 2) AS avg_4g_throughput FROM hive__npms__kpi_access4g_all_day_normal WHERE date = '2026-08-20';",
     "SELECT ROUND(AVG(CAST(dl_cell_throughput_mbps AS DOUBLE)), 2) AS avg_4g_throughput FROM hive.npms.kpi_access4g_all_day_normal WHERE date = '2026-08-20';",
     ["hive.npms.kpi_access4g_all_day_normal"], ["aggregation", "type_cast"]),
    ("E015", "Đếm số lượng cảnh báo có mức độ quan trọng là CRITICAL trong bảng gnoc.", "alarm",
     "SELECT COUNT(*) AS critical_count FROM hive__gnoc__gnoc WHERE level_important = 'CRITICAL';",
     "SELECT COUNT(*) AS critical_count FROM hive.gnoc.gnoc WHERE level_important = 'CRITICAL';",
     ["hive.gnoc.gnoc"], ["filtering", "aggregation"]),
    ("E016", "Liệt kê các mã khu vực (area_code) duy nhất có trong bảng f_location_new.", "common_location",
     "SELECT DISTINCT area_code FROM hive__netbi__f_location_new ORDER BY area_code;",
     "SELECT DISTINCT area_code FROM hive.netbi.f_location_new ORDER BY area_code;",
     ["hive.netbi.f_location_new"], ["distinct", "simple_lookup"]),
    ("E017", "Đếm số tài khoản FTTH có giới hạn đăng nhập (loginlimit) bằng 1.", "fbb",
     "SELECT COUNT(*) AS count_limit_1 FROM hive__aaa__ftth_account_pppoe WHERE loginlimit = '1';",
     "SELECT COUNT(*) AS count_limit_1 FROM hive.aaa.ftth_account_pppoe WHERE loginlimit = '1';",
     ["hive.aaa.ftth_account_pppoe"], ["filtering", "aggregation"]),
    ("E018", "Lấy 5 địa chỉ IP duy nhất đầu tiên được ghi nhận trong bảng accounting.", "fbb",
     "SELECT DISTINCT ip FROM hive__aaa__accounting ORDER BY ip LIMIT 5;",
     "SELECT DISTINCT ip FROM hive.aaa.accounting ORDER BY ip LIMIT 5;",
     ["hive.aaa.accounting"], ["distinct", "limit"]),
    ("E019", "Đếm số cell trong occean_cell có loại cell là '5G_NR'.", "network_kpi_5g",
     "SELECT COUNT(*) AS count_5g_ocean FROM hive__npms__occean_cell WHERE cell_type = '5G_NR';",
     "SELECT COUNT(*) AS count_5g_ocean FROM hive.npms.occean_cell WHERE cell_type = '5G_NR';",
     ["hive.npms.occean_cell"], ["filtering", "aggregation"]),
    ("E020", "Lấy danh sách 5 mã trạm phát sóng (station_code) duy nhất đầu tiên trong bảng gnoc.", "alarm",
     "SELECT DISTINCT station_code FROM hive__gnoc__gnoc ORDER BY station_code LIMIT 5;",
     "SELECT DISTINCT station_code FROM hive.gnoc.gnoc ORDER BY station_code LIMIT 5;",
     ["hive.gnoc.gnoc"], ["distinct", "limit"]),
]
print(f"Loaded {len(EASY_CASES)} Easy cases.")
