from __future__ import annotations
from typing import Protocol

class AuthorizationPort(Protocol):
    async def resolve_scope(self, user): ...
    async def assert_tables_allowed(self, scope, table_fqns: set[str]) -> None: ...

class CatalogPort(Protocol):
    async def search(self, query: str, scope, limit: int): ...
    async def hydrate_tables(self, fqns: list[str]): ...
    async def lineage(self, fqn: str, depth: int = 1): ...
    async def profiles(self, fqn: str): ...

class QueryLogPort(Protocol):
    async def search_validated_examples(self, query: str, scope, limit: int): ...
    async def join_priors(self, table_fqns: list[str]): ...

class LLMPort(Protocol):
    async def solve(self, request): ...
    async def verify_semantics(self, request): ...

class DatabaseGateway(Protocol):
    async def explain(self, context, sql: str): ...
    async def probe(self, context, probe): ...
    async def execute(self, context, sql: str): ...

class RiskPort(Protocol):
    async def decide(self, state): ...
